# Config file to manage bitcoin stats

[config]
logFile = "/tmp/bitcoin-stats.log"
sqliteLocation = ""
port = "9091"

# Kraken API Keys
[exchanges.kraken]
apiKey = ""
apiSecrey = ""

# Luno URL
[exchanges.luno]
url = "https://api.mybitx.com/api/1/tickers"

# Bitstamp URL
[exchanges.bitstamp]
url = "https://www.bitstamp.net/api/v2/ticker_hour/btcusd/"

# Bitfinex URL
[exchanges.bitfinex]
url = "https://api.bitfinex.com/v1/pubticker/"
tickers = "btcusd,ethbtc"

# Bittrex URL
[exchanges.bittrex]
url = "https://market.bisq.io/api/ticker"

# Bitsquare URL
[exchanges.bitsquare]
url = "https://market.bisq.io/api/ticker?market="
tickers = "btc_eur,btc_usd"

# BTCC URL
[exchanges.btcc]
url = "https://spotusd-data.btcc.com/data/pro/ticker?symbol="
tickers = "btcusd,"

# OKCoin URL
[exchanges.okcoin]
url = "https://www.okcoin.com/api/v1/ticker.do?symbol="
tickers = "btc_usd,"

# Poloniex URL
[exchanges.poloniex]
apiKey = ""
apiSecrey = ""
