# Config file to manage bitcoin stats

[config]
logFile = ""
sqliteLocation = ""

# Exchange specific configs
[exchanges]

# Kraken URL & API Keys
[exchanges.kraken]
url = ""
apiKey = ""
apiSecrey = ""

# Luno URL
[exchanges.luno]
url = ""

# Bitstamp URL
[exchanges.bitstamp]
url = ""

# Bitfinex URL
[exchanges.bitfinex]
url = ""
tickers = ""

# Bittrex URL
[exchanges.bittrex]
url = ""