# Config file to manage bitcoin stats

[config]
logFile = ""
sqliteLocation = ""

# Exchange specific configs
[exchanges]

# Kraken URL & API Keys
[exchanges.kraken]
url = ""
apiKey = ""
apiSecrey = ""

# Luno URL
[exchanges.luno]
url = ""
apiKey = ""
apiSecrey = ""

# Bitstamp URL
[exchanges.bitstamp]
url = ""